# Generated by Django 5.1.5 on 2025-03-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField(blank=True)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('employeeId', models.CharField(blank=True, db_index=True, max_length=15, unique=True)),
                ('contactNo', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentId', models.CharField(blank=True, max_length=20, unique=True)),
                ('documentName', models.CharField(max_length=100)),
                ('documentReason', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_received', to='doc_system.basicinfo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to='doc_system.basicinfo')),
            ],
        ),
    ]
